# Generated by Django 2.2.7 on 2019-12-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='iamge',
            new_name='image',
        ),
    ]
